[package]
name = "rstark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.4.1"
num-bigint = { version = "0.4.3", features = ["rand"] }
rand = "0.8.5"
serde = "1.0.183"
